### ISSUE TITLE
pytest-trio doesn't seem to be running a certain task

### ISSUE THREAD

**Issue by FFY00** [python-trio/pytest-trio#116]
Hi, I have an issue where a task that I registered doesn't seem to be run. I am having a hard time debugging it but it does seem like possibly there is something wrong with pytest-trio.

Consider the following code https://github.com/FFY00/dbus-objects/pull/17, particularly https://github.com/takluyver/dbus-objects/blob/trio/tests/test_jeepney_trio.py.
When I run the whole test suite, `test_listen` fails, but when I run the test alone it passes.

After registering the example tracer (https://trio.readthedocs.io/en/latest/tutorial.html#task-switching-illustrated), I noticed that the `dbus_objects.integration.jeepney.TrioDBusServer.listen` task is not being run.

Here are the outputs. I added a print in `listen` and before `send_and_get_reply`.

fail (`nox -s test-3.9`):
```
...
### new task spawned: dbus_objects.integration.jeepney.TrioDBusServer.listen
### task scheduled: dbus_objects.integration.jeepney.TrioDBusServer.listen
### task scheduled: <test 'test_listen_trio'>
<<< task step finished: <fixture 'jeepney_trio_server'>
### doing a quick check for I/O
### finished I/O check (took 1.8904975149780512e-05 seconds)
>>> about to run one step of task: dbus_objects.integration.jeepney.TrioDBusServer.listen
listening!
<<< task step finished: dbus_objects.integration.jeepney.TrioDBusServer.listen
>>> about to run one step of task: <test 'test_listen_trio'>
### task scheduled: <test 'test_listen_trio'>
<<< task step finished: <test 'test_listen_trio'>
### doing a quick check for I/O
### finished I/O check (took 8.080009138211608e-06 seconds)
>>> about to run one step of task: <test 'test_listen_trio'>
sending...
### task scheduled: jeepney.io.trio.DBusRouter._sender
### task scheduled: <test 'test_listen_trio'>
<<< task step finished: <test 'test_listen_trio'>
### doing a quick check for I/O
### finished I/O check (took 8.670001989230514e-06 seconds)
>>> about to run one step of task: <test 'test_listen_trio'>
<<< task step finished: <test 'test_listen_trio'>
>>> about to run one step of task: jeepney.io.trio.DBusRouter._sender
### task scheduled: jeepney.io.trio.DBusRouter._sender
<<< task step finished: jeepney.io.trio.DBusRouter._sender
### doing a quick check for I/O
### finished I/O check (took 7.019989425316453e-06 seconds)
>>> about to run one step of task: jeepney.io.trio.DBusRouter._sender
### task scheduled: jeepney.io.trio.DBusRouter._sender
<<< task step finished: jeepney.io.trio.DBusRouter._sender
### doing a quick check for I/O
### finished I/O check (took 7.277005352079868e-06 seconds)
>>> about to run one step of task: jeepney.io.trio.DBusRouter._sender
<<< task step finished: jeepney.io.trio.DBusRouter._sender
### waiting for I/O for up to 86400 seconds
(it blocks here)
```

success (`nox -s test-3.9 -- -k 'test_listen and trio'`):
```
...
### new task spawned: dbus_objects.integration.jeepney.TrioDBusServer.listen
### task scheduled: dbus_objects.integration.jeepney.TrioDBusServer.listen
### task scheduled: <test 'test_listen_trio'>
<<< task step finished: <fixture 'jeepney_trio_server'>
### doing a quick check for I/O
### finished I/O check (took 8.900999091565609e-06 seconds)
>>> about to run one step of task: <test 'test_listen_trio'>
### task scheduled: <test 'test_listen_trio'>
<<< task step finished: <test 'test_listen_trio'>
>>> about to run one step of task: dbus_objects.integration.jeepney.TrioDBusServer.listen
listening!
<<< task step finished: dbus_objects.integration.jeepney.TrioDBusServer.listen
### doing a quick check for I/O
### finished I/O check (took 8.464005077257752e-06 seconds)
>>> about to run one step of task: <test 'test_listen_trio'>
sending...
### task scheduled: jeepney.io.trio.DBusRouter._sender
### task scheduled: <test 'test_listen_trio'>
<<< task step finished: <test 'test_listen_trio'>
### doing a quick check for I/O
### finished I/O check (took 8.01600981503725e-06 seconds)
>>> about to run one step of task: <test 'test_listen_trio'>
<<< task step finished: <test 'test_listen_trio'>
>>> about to run one step of task: jeepney.io.trio.DBusRouter._sender
### task scheduled: jeepney.io.trio.DBusRouter._sender
<<< task step finished: jeepney.io.trio.DBusRouter._sender
### doing a quick check for I/O
### finished I/O check (took 7.2270049713552e-06 seconds)
>>> about to run one step of task: jeepney.io.trio.DBusRouter._sender
### task scheduled: jeepney.io.trio.DBusRouter._sender
<<< task step finished: jeepney.io.trio.DBusRouter._sender
### doing a quick check for I/O
### task scheduled: dbus_objects.integration.jeepney.TrioDBusServer.listen
### finished I/O check (took 3.3025979064404964e-05 seconds)
>>> about to run one step of task: jeepney.io.trio.DBusRouter._sender
<<< task step finished: jeepney.io.trio.DBusRouter._sender
>>> about to run one step of task: dbus_objects.integration.jeepney.TrioDBusServer.listen
received!
### task scheduled: dbus_objects.integration.jeepney.TrioDBusServer.listen
<<< task step finished: dbus_objects.integration.jeepney.TrioDBusServer.listen
```

Am I missing something obvious here? Am I mishandling the API somehow? I have no good ideas right now, I have no clue why the `dbus_objects.integration.jeepney.TrioDBusServer.listen` task isn't being scheduled...

The code for `send_and_get_reply` can be found at https://gitlab.com/takluyver/jeepney/-/blob/master/jeepney/io/trio.py#L153.

I am sorry if this is not caused by pytest-trio, but I really am having a hard time tracking down the source.

**Comment by njsmith** [comment]
>  When I run the whole test suite, test_listen fails, but when I run the test alone it passes.

Well, that certainly sounds suspicious...

I looked over your test file and nothing obvious jumped out at me.

Random shot in the dark: does it help if you use `@pytest_trio.trio_fixture` instead of `@pytest.fixture` on your trio fixtures? In theory it shouldn't matter since `test_listen` has the `trio` mark on it, and that should cause pytest-trio to automatically claim all async fixtures that it uses, but just in case...

**Comment by FFY00** [comment]
Nop, it doesn't change anything :confused:

**Comment by FFY00** [comment]
Note, after I ctrl+c the task gets scheduled.

```
### task scheduled: <TrioToken.run_sync_soon task>
### finished I/O check (took 27.49495120998472 seconds)
>>> about to run one step of task: <TrioToken.run_sync_soon task>
### task scheduled: <fixture 'jeepney_trio_router'>
### task scheduled: jeepney.io.trio.DBusRouter._receiver
### task scheduled: jeepney.io.trio.DBusRouter._sender
### task scheduled: <fixture 'nursery'>
### task scheduled: <test 'test_listen_trio'>
### task scheduled: dbus_objects.integration.jeepney.TrioDBusServer.listen
### task scheduled: <fixture 'jeepney_trio_server'>
<<< task step finished: <TrioToken.run_sync_soon task>
```

**Comment by FFY00** [comment]
Is there anything else I can do to debug?

**Comment by njsmith** [comment]
Hmm, from your "fail" log above, I notice it says:

```
>>> about to run one step of task: dbus_objects.integration.jeepney.TrioDBusServer.listen
listening!
<<< task step finished: dbus_objects.integration.jeepney.TrioDBusServer.listen
```

...so it looks like the `dbus_objects.integration.jeepney.TrioDBusServer.listen` task *is* running? The problem is that after you send the message, the `listen` task never wakes up to receive it, like the message isn't actually arriving.

Is it possible you have some kind of race condition, where there's a gap between when you start the listen task and when it can actually receive messages, and sometimes the message arrives during that gap before it's properly started, and gets lost?

**Comment by njsmith** [comment]
...on which note, it might be interesting to see a trace of the dbus traffic (e.g. `dbus-monitor --session`), or the raw traffic going over the listener's connection to the dbus server.

**Comment by FFY00** [comment]
Perhaps, but I added a `await trio.sleep(3)` in the fixure and it is still the same.

I was also looking at dbus-monitor, I only see the request.

```
method call time=1613972484.910687 sender=:1.806 -> destination=io.github.ffy00.dbus-objects.tests serial=2 path=/io/github/ffy00/dbus_objects/example; interface=com.example.object.ExampleObject; member=Ping
```

Which supports my suspicion, as shown in the tracer output the listen task isn't being scheduled. It is started and is scheduled one time, but it is not scheduled again, which means the code listen doesn't run and the server never replies.

Trio is responsible for this scheduling, right? Where can I find the scheduling logic? Is there any better way for me to debug this?

**Comment by FFY00** [comment]
Uh, it seems it is a problem with DBus tearing down other test that happens to use the same name. Sorry for the trouble.
