### ISSUE TITLE
Advantages/disadvantages of hooking pytest_pyfunc_call versus pytest_collection_modifyitems?

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#13]
In my previous hacks, like trio's own `conftest.py`, I hooked `pytest_pyfunc_call` instead of `pytest_collection_modifyitems` (like pytest-asyncio does, and the current version of pytest-trio does as well). Possibly this is a bit simpler? Are there any other advantages/disadvantages to doing things this way?

CC @Tinche -- do you know why pytest-asyncio chose `pytest_collection_modifyitems` in the first place?

**Comment by touilleMan** [comment]
My understanding is having multiple `pytest_collection_modifyitems` is easier to multiple `pytest_pyfunc_call`.
- `pytest_collection_modifyitems` are called one after another
- `pytest_pyfunc_call` does nested calls (when using with yield) or can even shadow each other (pytest uses the first available)

From this, I would say using `pytest_collection_modifyitems` is better than `pytest_pyfunc_call` in a library given you never know what other installed plugins can mess with you.

Besides, nested calls with `pytest_pyfunc_call` bring a more complicated workflow when debugging (bigger stacktrace each layer doing pretty unrelated stuff).

**Comment by Tinche** [comment]
Honestly I lifted this part wholesale from pytest-tornado, so I'm not sure. Also it looks to me pytest-asyncio actually uses `pytest_pyfunc_call`?

**Comment by njsmith** [comment]
@Tinche Oh sorry, yeah, looking again at pytest-asyncio I was clearly misremembering, you do something else again. This is pretty messy! I think I was mixing up some memory of your `pytest_pycollect_makeitem` with our `pytest_pycollect_modifyitems`.

BTW, is pytest-asyncio's `pytest_pycollect_makeitem` hook doing anything at all these days? It kinda looks like a complicated no-op to me.

@touilleMan That makes sense. Probably we should move our `pytest_pycollection_modifyitems` hook to run *last* though instead of first, in case anyone else is using that hook to mess with marks? In particular we might want to use that hook mess with marks for #9...
