### ISSUE TITLE
Nervous about the auto-upload-to-pypi feature

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#2]
I'm nervous about your use of Travis's auto-upload-to-pypi feature.

The problem is that right now, anyone who has write access to this repo can upload arbitrary packages to pypi using your username/password, without telling anyone or generating any notifications at all -- all they have to do is directly push a commit to this repo under some new branch.

I'm not sure, but they might also be able to directly read out your pypi password and then do whatever they want with it.

I don't think anyone will *actually* do this, but we have a [very liberal policy for handing out write access](https://trio.readthedocs.io/en/latest/contributing.html#joining-the-team), and part of the idea for making that work is to make sure that what we're actually handing out is just the ability to merge pull requests, so even if someone did decide to be evil then they'd still have to do that by submitting an evil PR, which would send everyone notifications and we'd roll it back immediately. But this doesn't work for the auto-pypi feature. (I *really* wish github had the ability to entirely disable direct pushes to a repo, but alas it does not.)

Anyway, this means that right now there are 10 people with write access to this repo = 10 people who you may have just given your pypi password to... maybe it would be better to disable that feature and change your pypi password?

**Comment by njsmith** [comment]
Oh, it also doesn't work with `towncrier`...

**Comment by touilleMan** [comment]
My password is protected by travis [encrypt variable](https://docs.travis-ci.com/user/encryption-keys/) feature. Beside only build triggered by the main repo will contain the variable. So my password *should be* safe.

However I can totally understand your concern on the release system.
I think the easiest thing to do is you provide me your pypi login and I add you to the project there. This way we can both release new version, then I remove the travis release system.

**Comment by njsmith** [comment]
> My password is protected by travis encrypt variable feature. Beside only build triggered by the main repo will contain the variable. So my password should be safe.

Sure, only Travis can decrypt it. But anyone who can commit to the repo can ask Travis to use the decrypted password to perform arbitrary actions, and Travis will happily do them...

If this were an encrypted envvar, then it would be trivial to get the password: just upload a travis script that does `echo $ENVVAR` :-). Since it's a deploy key, I'm not sure if there's a way to get it or not. But it's entirely possible there is one. (For example, if you put that magic `secure: ...` string into an `env:` section, it won't be a valid environment variable, but maybe the error message will include the decrypted password?) I'd probably change my password anyway, just to be sure...

**Comment by touilleMan** [comment]
> If this were an encrypted envvar, then it would be trivial to get the password: just upload a travis script that does echo $ENVVAR :-)

That's true. However [secure env var are disabled on PR](https://docs.travis-ci.com/user/encryption-keys/) so this malicious code must be added by someone with write credentials on the repo. I guess the risk gets higher every time a contributor is added to the project ;-)
