### ISSUE TITLE
codecov working as expected ?

### ISSUE THREAD

**Issue by touilleMan** [python-trio/pytest-trio#21]
[Looking for code coverage report](https://codecov.io/gh/python-trio/pytest-trio/src/979d4d4ab4626d9fde1a4aa4b72e20a09891d262/pytest_trio/plugin.py), it seems top level code isn't considered as covered.

@njsmith I have no experience with codecov (I use coverall on my personal projects), is there something I've missed ?

**Comment by touilleMan** [comment]
I've reproduce this on local, so it's not codecov's fault but on coverage/pytest-cov side.

**Comment by njsmith** [comment]
Does the pytester plugin run subprocesses? It could be that they're all writing coverage information into the same file, and overwriting each other...

If that's it, then the solution is to add `parallel = True` to the `.coveragerc`, and then run `coverage combine` between running the tests and uploading to pypi. Trio does this, so you can check its `.coveragerc`, `.appveyor.yml`, `ci/travis.sh` to see the details.

**Comment by touilleMan** [comment]
I've got the trouble: we are testing a pytest plugin (i.e. `pytest-trio`) with pytest, using another pytest plugin (`pytest-cov`) so coverage work is started after `pytest-trio` is loaded.
The solution is to start the coverage before `pytest-trio` is loaded, so before pytest is called:
```
$ coverage -m pytest
```

**Comment by njsmith** [comment]
Ha! Nice catch :-)
