### ISSUE TITLE
Administrivia

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#3]
* Can you give me "owner" rights to pytest-trio on pypi, so that in case you're out of touch at some point, I can manage it? I think that should be on [this page](https://pypi.python.org/pypi?:action=role_form&package_name=pytest-trio), and my PyPI username is "njs".

* I'd like to enable branch protection on this repo, like we have on the other trio repos -- this would mean that all changes have to come in through PRs. Does that work for you?

**Comment by touilleMan** [comment]
- You're owner on pypi now
- Branch protection works for me, I let you enable this :+1:

**Comment by njsmith** [comment]
Okay, branch protection is enabled now
