### ISSUE TITLE
blocks testing of Trio

### ISSUE THREAD

**Issue by smurfix** [python-trio/pytest-trio#31]
Apparently, installing trio plus pytest-trio causes trio to be untestable.

Please fix.

```dev /src/trio$ PYTHONPATH=. py.test-3 -sxv trio/tests
================================================ test session starts =================================================
platform linux -- Python 3.6.4, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python3
cachedir: .cache
rootdir: /src/trio, inifile:
plugins: trio-0.3.0, pylint-0.6.0, pep8-1.0.6, mock-1.3.0, cov-2.4.0, asyncio-0.2.0
collected 248 items                                                                                                   

trio/tests/test_abc.py::test_AsyncResource_defaults PASSED
trio/tests/test_deprecate.py::test_warn_deprecated FAILED

====================================================== FAILURES ======================================================
________________________________________________ test_warn_deprecated ________________________________________________

item = <Function 'test_warn_deprecated'>

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_call(item):
        if 'trio' in item.keywords:
            if not iscoroutinefunction(item.obj):
                pytest.fail(
>                   'test function `%r` is marked trio but is not async' % item
                )
E               Failed: test function `<Function 'test_warn_deprecated'>` is marked trio but is not async

/usr/lib/python3/dist-packages/pytest_trio/plugin.py:215: Failed
```

**Comment by njsmith** [comment]
Whoa, what the heck. That function doesn't have a `pytest.mark.trio` on it it anything... Maybe we're misunderstanding what `item.keywords` does?

**Comment by njsmith** [comment]
It looks like the examples here use `item.get_marker("name")` instead of `item.keywords`

https://docs.pytest.org/en/latest/example/markers.html#passing-a-callable-to-custom-markers

**Comment by touilleMan** [comment]
I think I got the trouble, see here http://tox.readthedocs.io/en/latest/example/pytest.html#known-issues-and-limitations

Pytest tries to load the modules to test by there fully qualified name, but this can clash if there is already a module with a similar name present in the PYTHONPATH.

In our case, we are working on trio (so trio is doesn't need to be installed in our venv given we will run pytest from the project folder), but when installing pytest-trio pip also install trio given it is listed as dependency. Hence we end up with 2 different trio modules :-(

The solution is to `pip install -e .` the trio project so the dependency is satisfied.
