### ISSUE TITLE
Multiple CI platforms ?

### ISSUE THREAD

**Issue by touilleMan** [python-trio/pytest-trio#39]
We've just got a pretty nasty bug with CI on MacOS (see #37) that caused me time and frustration :cry: 
This lead me to wonder what is our policy to decide which platform should be CI tested.

In theory the more the better, however more platform means more exotic ci-specific code to support, more platform-specific crashes to debug (especially non linux platforms, which are often hard to reproduce locally) and more pain waiting for CI to finish ^^

I would say the gain outweigh the cost for libraries dealing with low level stuff like trio does (that's why I opened https://github.com/python-trio/trio/issues/498).
However for pytest-trio I fell like platform differences should be almost non-existent (given the codebase and our dependencies)

A middleground would be to keep multi-platform support, but keep it to it minimal (one windows and one macOS build with last CPython for instance)

**Comment by touilleMan** [comment]
> I guess there is one rule: if you discover that you have a bug that you would have found, but didn't, because you were missing a CI entry, then that means you should add the CI entry :-).

I like this rule ;-)

> Is running multiple tests on Windows causing any problems, e.g.?

Windows works pretty well on this project so far (but I'm personally still recovering from a really painful appveyor debugging on another project 😄 )

**Comment by njsmith** [comment]
Appveyor debugging is the worst, yeah :-(. Fyi, it's not *too* hard to get a local Windows vm set up, and it makes Windows debugging infinitely easier. (MS actually provides free vm images.) Let me know if you ever want more details.
