### ISSUE TITLE
Current capabilities?

### ISSUE THREAD

**Issue by zmitchell** [python-trio/pytest-trio#41]
I can see that this is a work in progress, but I'm wondering what the current status is. What does the package provide?

**Comment by zmitchell** [comment]
Do I need to import anything to use `pytest.mark.trio`, or will `pytest` discover it automatically? I made a fixture with `pytest.mark.fixture` and the fixture wasn't discovered.

**Comment by njsmith** [comment]
You don't need to import anything, just have pytest-trio installed in the same environment as pytest. When pytest starts up I think it prints a list of all the plugins it discovered, and if pytest-trio is there then you're good.

The other issue is my fault: it should be `pytest.fixture`, not `pytest.mark.fixture`. Sorry!
