### ISSUE TITLE
Problem running trio's tests when pytest-trio is installed

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#43]
I'm not sure exactly how to reproduce this, but there's some discussion between @tgoodlet and @smurfix here: https://gitter.im/python-trio/general?at=5b213da437a2df7bed39c33b

My suspicion is that the problem is currently pytest-trio checks whether a test has `trio` as a *keyword*, and that this is slightly different than having `trio` as a *mark*. If that's right, then the solution is to switch to using `get_marker` or the newer `get_closest_marker`: https://docs.pytest.org/en/latest/mark.html#marker-revamp-and-iteration

**Comment by tgoodlet** [comment]
I'll gladly take this for the weekend :)
