### ISSUE TITLE
trio.ClosedResourceError with chained async fixtures

### ISSUE THREAD

**Issue by belm0** [python-trio/pytest-trio#63]
The following structure often produces `trio.ClosedResourceError` at the end of test functions.

```
@pytest.fixture
async def server(nursery):
    server = Server()  # pure Trio
    await nursery.start(server.serve)
    yield server
    server.close()

@pytest.fixture
async def client(server):
    async with open_client('127.0.0.1', server.port) as client:  # also pure Trio
        yield client

async test_foo(server, client, autojump_clock):
    pass
```
If I combine fixtures, the problem goes away:
```
@pytest.fixture
async def client_server(nursery):
    server = Server()
    await nursery.start(server.serve)
    async with open_client('127.0.0.1', server.port) as client:
        yield (client, server)
    server.close()

async test_foo(client_server, autojump_clock):
    pass
```

**Comment by belm0** [comment]
It occurs even if I change the body of all test methods to `pass`.

**Comment by njsmith** [comment]
Looks like the crash is in `trio_websocket`, when the server's writer task tries to send some data at the same time that the server has already closed the connection (presumably in the main task). My guess is that this is a symptom of `trio_websocket` not having a carefully-thought-through shutdown procedure. Not sure why it's only showing up with some fixture configurations, though.

**Comment by belm0** [comment]
Ah, totally missed that.  `trio_websocket` has my patch to`listen()` https://github.com/HyperionGray/trio-websocket/pull/10.  It appears I threw in a `sleep_forever()` without thinking about the shutdown case.

**Comment by belm0** [comment]
Ok, it happens regardless of my patch.  Agreed it's shutdown issues in the trio-websocket design.  Thank you!
