### ISSUE TITLE
Recent pytest now issues a warning with our conftest.py, breaking our CI

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#66]
See: https://github.com/pytest-dev/pytest/issues/4039

And since we use `-W error`, this breaks everything in CI...

**Comment by altendky** [comment]
It looks like the workaround has been removed in https://github.com/python-trio/pytest-trio/commit/75f1a0dc79a1a40b8e9d22cfb925542cc4d8a446 so this could be close?

**Comment by pquentin** [comment]
Right, the CI passes now
