### ISSUE TITLE
Test on python 3.7

### ISSUE THREAD

**Issue by njsmith** [python-trio/pytest-trio#70]
It looks like we don't have 3.7 in our test matrix currently. We should fix that.

**Comment by altendky** [comment]
Looks like it got covered.  Though 3.9 could use some attention...  #109

https://github.com/python-trio/pytest-trio/blob/57f458dc59468b9cf88deb6c21791c1ee0a15673/.travis.yml#L8-L9
https://github.com/python-trio/pytest-trio/blob/57f458dc59468b9cf88deb6c21791c1ee0a15673/.appveyor.yml#L9-L10
